import type { AppData } from "./types";

export const seedData: AppData = {
  company: {
    id: "co_apex",
    name: "Apex Metalworks",
    industry: "Metal fabrication & components",
    plan: "growth",
    plants: ["Plant A — Houston"],
  },
  user: {
    id: "u_owner",
    name: "Jordan Hale",
    email: "jordan@apexmetalworks.com",
    role: "owner",
    department: "Executive",
    avatarInitials: "JH",
  },
  customers: [
    {
      id: "c1",
      company: "Northline Automotive",
      contact: "Priya Shah",
      phone: "+1 713-555-0142",
      email: "priya@northline.auto",
      industry: "Automotive",
      creditLimit: 250000,
      paymentTerms: "Net 30",
      outstanding: 43200,
      stage: "sales_order",
      lifetimeValue: 890000,
    },
    {
      id: "c2",
      company: "Gulf Coast Energy",
      contact: "Marcus Webb",
      phone: "+1 281-555-0198",
      email: "m.webb@gulfcoast.energy",
      industry: "Energy",
      creditLimit: 500000,
      paymentTerms: "Net 45",
      outstanding: 12800,
      stage: "quotation",
      lifetimeValue: 1240000,
    },
    {
      id: "c3",
      company: "Riverton Appliances",
      contact: "Elena Cruz",
      phone: "+1 832-555-0111",
      email: "elena@riverton.com",
      industry: "Consumer goods",
      creditLimit: 100000,
      paymentTerms: "Net 15",
      outstanding: 0,
      stage: "negotiation",
      lifetimeValue: 210000,
    },
    {
      id: "c4",
      company: "Summit HVAC",
      contact: "Tom Brennan",
      phone: "+1 214-555-0177",
      email: "tom@summithvac.com",
      industry: "HVAC",
      creditLimit: 150000,
      paymentTerms: "Net 30",
      outstanding: 8600,
      stage: "lead",
      lifetimeValue: 45000,
    },
    {
      id: "c5",
      company: "Pacific Rail Parts",
      contact: "Amy Chen",
      phone: "+1 510-555-0133",
      email: "amy@pacificrail.com",
      industry: "Rail",
      creditLimit: 300000,
      paymentTerms: "Net 30",
      outstanding: 22100,
      stage: "production",
      lifetimeValue: 670000,
    },
  ],
  suppliers: [
    {
      id: "s1",
      company: "Texas Steel Supply",
      contact: "Dave Ortiz",
      phone: "+1 713-555-0201",
      email: "dave@txsteel.com",
      paymentTerms: "Net 30",
      rating: 4.6,
      leadTimeDays: 5,
    },
    {
      id: "s2",
      company: "Polymer Plus",
      contact: "Sara Kim",
      phone: "+1 832-555-0222",
      email: "sara@polymerplus.com",
      paymentTerms: "Net 21",
      rating: 4.2,
      leadTimeDays: 7,
    },
    {
      id: "s3",
      company: "FastenRight Co.",
      contact: "Luis Romero",
      phone: "+1 281-555-0233",
      email: "luis@fastenright.com",
      paymentTerms: "Net 15",
      rating: 4.8,
      leadTimeDays: 3,
    },
  ],
  products: [
    {
      id: "p_steel",
      sku: "RM-STL-2MM",
      name: "Steel Sheet 2mm",
      category: "raw_material",
      unit: "KG",
      quantity: 3800,
      reserved: 300,
      minStock: 400,
      reorderPoint: 500,
      warehouse: "Warehouse A",
      bin: "A-12-04",
      batch: "B-8821",
      supplierId: "s1",
      unitCost: 1.85,
    },
    {
      id: "p_plastic",
      sku: "RM-PL-ABS",
      name: "ABS Plastic Pellets",
      category: "raw_material",
      unit: "KG",
      quantity: 2100,
      reserved: 150,
      minStock: 300,
      reorderPoint: 400,
      warehouse: "Warehouse A",
      bin: "A-08-02",
      supplierId: "s2",
      unitCost: 2.4,
    },
    {
      id: "p_screw",
      sku: "RM-SCR-M6",
      name: "M6 Hex Screws",
      category: "component",
      unit: "PCS",
      quantity: 48000,
      reserved: 12000,
      minStock: 10000,
      reorderPoint: 15000,
      warehouse: "Warehouse A",
      bin: "A-03-11",
      supplierId: "s3",
      unitCost: 0.08,
    },
    {
      id: "p_paint",
      sku: "RM-PNT-BLK",
      name: "Industrial Paint Black",
      category: "raw_material",
      unit: "L",
      quantity: 620,
      reserved: 80,
      minStock: 100,
      reorderPoint: 150,
      warehouse: "Warehouse A",
      bin: "A-15-01",
      unitCost: 6.5,
    },
    {
      id: "p_pack",
      sku: "PK-BOX-MED",
      name: "Medium Packaging Box",
      category: "packaging",
      unit: "PCS",
      quantity: 3400,
      reserved: 500,
      minStock: 800,
      reorderPoint: 1000,
      warehouse: "Warehouse A",
      bin: "A-20-03",
      unitCost: 0.55,
    },
    {
      id: "p_bracket",
      sku: "FG-BRK-100",
      name: "Mounting Bracket A",
      category: "finished_goods",
      unit: "PCS",
      quantity: 1860,
      reserved: 400,
      minStock: 200,
      reorderPoint: 350,
      warehouse: "Warehouse B",
      bin: "B-01-05",
      unitCost: 28,
      sellPrice: 40,
    },
    {
      id: "p_housing",
      sku: "FG-HSG-220",
      name: "Motor Housing X",
      category: "finished_goods",
      unit: "PCS",
      quantity: 420,
      reserved: 120,
      minStock: 80,
      reorderPoint: 120,
      warehouse: "Warehouse B",
      bin: "B-02-01",
      unitCost: 64,
      sellPrice: 95,
    },
    {
      id: "p_wip_bracket",
      sku: "WIP-BRK-100",
      name: "Bracket A — Assembly WIP",
      category: "wip",
      unit: "PCS",
      quantity: 310,
      reserved: 0,
      minStock: 0,
      reorderPoint: 0,
      warehouse: "Warehouse A",
      bin: "WIP-04",
      unitCost: 22,
    },
  ],
  boms: [
    {
      id: "bom1",
      productId: "p_bracket",
      version: "v3.2",
      lines: [
        { productId: "p_steel", quantity: 5 },
        { productId: "p_plastic", quantity: 2 },
        { productId: "p_screw", quantity: 12 },
        { productId: "p_paint", quantity: 0.5 },
        { productId: "p_pack", quantity: 1 },
      ],
    },
    {
      id: "bom2",
      productId: "p_housing",
      version: "v1.8",
      lines: [
        { productId: "p_steel", quantity: 12 },
        { productId: "p_plastic", quantity: 4 },
        { productId: "p_screw", quantity: 24 },
        { productId: "p_paint", quantity: 1.2 },
        { productId: "p_pack", quantity: 1 },
      ],
    },
  ],
  quotations: [
    {
      id: "q1",
      number: "QT-1023",
      customerId: "c2",
      date: "2026-08-18",
      validUntil: "2026-09-01",
      lines: [
        { productId: "p_bracket", quantity: 100, unitPrice: 40 },
        { productId: "p_housing", quantity: 50, unitPrice: 95 },
      ],
      taxRate: 0.1,
      discount: 100,
      status: "sent",
    },
    {
      id: "q2",
      number: "QT-1021",
      customerId: "c3",
      date: "2026-08-12",
      validUntil: "2026-08-26",
      lines: [{ productId: "p_bracket", quantity: 500, unitPrice: 38 }],
      taxRate: 0.1,
      discount: 250,
      status: "accepted",
    },
    {
      id: "q3",
      number: "QT-1018",
      customerId: "c1",
      date: "2026-08-05",
      validUntil: "2026-08-20",
      lines: [{ productId: "p_housing", quantity: 200, unitPrice: 92 }],
      taxRate: 0.1,
      discount: 0,
      status: "converted",
    },
  ],
  salesOrders: [
    {
      id: "so1",
      number: "SO-8841",
      customerId: "c1",
      quotationId: "q3",
      date: "2026-08-08",
      dueDate: "2026-09-12",
      lines: [{ productId: "p_housing", quantity: 200, unitPrice: 92 }],
      status: "in_production",
    },
    {
      id: "so2",
      number: "SO-8844",
      customerId: "c5",
      date: "2026-08-14",
      dueDate: "2026-09-05",
      lines: [{ productId: "p_bracket", quantity: 1000, unitPrice: 40 }],
      status: "confirmed",
    },
    {
      id: "so3",
      number: "SO-8830",
      customerId: "c1",
      date: "2026-07-22",
      dueDate: "2026-08-20",
      lines: [{ productId: "p_bracket", quantity: 400, unitPrice: 40 }],
      status: "invoiced",
    },
    {
      id: "so4",
      number: "SO-8825",
      customerId: "c2",
      date: "2026-07-10",
      dueDate: "2026-08-01",
      lines: [{ productId: "p_housing", quantity: 80, unitPrice: 95 }],
      status: "paid",
    },
  ],
  purchaseOrders: [
    {
      id: "po1",
      number: "PO-4412",
      supplierId: "s1",
      date: "2026-08-20",
      expectedDate: "2026-08-27",
      lines: [{ productId: "p_steel", quantity: 1200, unitCost: 1.92 }],
      status: "ordered",
      total: 2304,
    },
    {
      id: "po2",
      number: "PO-4408",
      supplierId: "s3",
      date: "2026-08-15",
      expectedDate: "2026-08-18",
      lines: [{ productId: "p_screw", quantity: 20000, unitCost: 0.075 }],
      status: "received",
      total: 1500,
    },
    {
      id: "po3",
      number: "PO-4401",
      supplierId: "s2",
      date: "2026-08-10",
      expectedDate: "2026-08-17",
      lines: [{ productId: "p_plastic", quantity: 800, unitCost: 2.55 }],
      status: "inspected",
      total: 2040,
    },
    {
      id: "po4",
      number: "PO-4395",
      supplierId: "s1",
      date: "2026-08-01",
      expectedDate: "2026-08-08",
      lines: [{ productId: "p_steel", quantity: 2000, unitCost: 1.8 }],
      status: "paid",
      total: 3600,
    },
  ],
  productionOrders: [
    {
      id: "pr1",
      number: "PR-1023",
      productId: "p_housing",
      salesOrderId: "so1",
      quantity: 200,
      deadline: "2026-09-12",
      status: "delayed",
      materialsReady: true,
      machineReady: true,
      laborReady: true,
      progress: 62,
      machineId: "m2",
    },
    {
      id: "pr2",
      number: "PR-1026",
      productId: "p_bracket",
      salesOrderId: "so2",
      quantity: 1000,
      deadline: "2026-09-05",
      status: "materials_check",
      materialsReady: false,
      machineReady: true,
      laborReady: true,
      progress: 0,
      machineId: "m1",
    },
    {
      id: "pr3",
      number: "PR-1019",
      productId: "p_bracket",
      quantity: 500,
      deadline: "2026-08-28",
      status: "in_production",
      materialsReady: true,
      machineReady: true,
      laborReady: true,
      progress: 74,
      machineId: "m1",
    },
    {
      id: "pr4",
      number: "PR-1015",
      productId: "p_housing",
      quantity: 100,
      deadline: "2026-08-22",
      status: "quality_check",
      materialsReady: true,
      machineReady: true,
      laborReady: true,
      progress: 100,
      machineId: "m2",
    },
    {
      id: "pr5",
      number: "PR-1010",
      productId: "p_bracket",
      quantity: 800,
      deadline: "2026-08-15",
      status: "completed",
      materialsReady: true,
      machineReady: true,
      laborReady: true,
      progress: 100,
      machineId: "m3",
    },
  ],
  workOrders: [
    { id: "wo1", productionOrderId: "pr3", stage: "Cutting", department: "Fabrication", status: "done", assignee: "Mike Torres", sequence: 1 },
    { id: "wo2", productionOrderId: "pr3", stage: "Machining", department: "Machining", status: "done", assignee: "Ana Lopez", sequence: 2 },
    { id: "wo3", productionOrderId: "pr3", stage: "Assembly", department: "Assembly", status: "in_progress", assignee: "Chris Park", sequence: 3 },
    { id: "wo4", productionOrderId: "pr3", stage: "Painting", department: "Finishing", status: "pending", sequence: 4 },
    { id: "wo5", productionOrderId: "pr3", stage: "Quality Control", department: "QC", status: "pending", sequence: 5 },
    { id: "wo6", productionOrderId: "pr3", stage: "Packaging", department: "Warehouse", status: "pending", sequence: 6 },
    { id: "wo7", productionOrderId: "pr1", stage: "Cutting", department: "Fabrication", status: "done", assignee: "Mike Torres", sequence: 1 },
    { id: "wo8", productionOrderId: "pr1", stage: "Machining", department: "Machining", status: "in_progress", assignee: "Ana Lopez", sequence: 2 },
    { id: "wo9", productionOrderId: "pr1", stage: "Assembly", department: "Assembly", status: "pending", sequence: 3 },
  ],
  machines: [
    {
      id: "m1",
      name: "CNC Press #07",
      location: "Bay 2",
      status: "running",
      capacityPerHour: 85,
      runtimeHours: 8.2,
      efficiency: 87,
      nextMaintenanceHours: 32,
    },
    {
      id: "m2",
      name: "Laser Cutter #03",
      location: "Bay 1",
      status: "running",
      capacityPerHour: 40,
      runtimeHours: 6.5,
      efficiency: 71,
      nextMaintenanceHours: 12,
    },
    {
      id: "m3",
      name: "Assembly Cell A",
      location: "Bay 4",
      status: "idle",
      capacityPerHour: 60,
      runtimeHours: 4.1,
      efficiency: 92,
      nextMaintenanceHours: 48,
    },
    {
      id: "m4",
      name: "Paint Booth #02",
      location: "Bay 5",
      status: "maintenance",
      capacityPerHour: 30,
      runtimeHours: 0,
      efficiency: 0,
      nextMaintenanceHours: 0,
    },
  ],
  maintenance: [
    {
      id: "mt1",
      machineId: "m4",
      type: "corrective",
      problem: "Nozzle clog / uneven spray",
      reportedBy: "Finishing Lead",
      date: "2026-08-25",
      technician: "Ravi Patel",
      partsCost: 280,
      downtimeHours: 6,
      resolution: "Nozzle replaced; calibration pending",
      status: "in_progress",
    },
    {
      id: "mt2",
      machineId: "m2",
      type: "preventive",
      problem: "Scheduled lens & rail service",
      reportedBy: "System",
      date: "2026-08-28",
      technician: "Ravi Patel",
      partsCost: 120,
      downtimeHours: 0,
      resolution: "Scheduled",
      status: "open",
    },
  ],
  qualityChecks: [
    {
      id: "qc1",
      reference: "PO-4401",
      stage: "raw_material",
      batch: "B-9912",
      inspector: "Nina Brooks",
      inspected: 800,
      rejected: 12,
      defect: "Moisture content high",
      correctiveAction: "Quarantine & re-dry",
      date: "2026-08-18",
      status: "conditional",
    },
    {
      id: "qc2",
      reference: "PR-1015",
      stage: "final",
      batch: "B-7740",
      inspector: "Nina Brooks",
      inspected: 100,
      rejected: 3,
      defect: "Tolerance out on flange",
      correctiveAction: "Rework machining",
      date: "2026-08-24",
      status: "fail",
    },
    {
      id: "qc3",
      reference: "PR-1010",
      stage: "final",
      batch: "B-7721",
      inspector: "Omar Diaz",
      inspected: 800,
      rejected: 4,
      date: "2026-08-15",
      status: "pass",
    },
    {
      id: "qc4",
      reference: "SO-8830",
      stage: "dispatch",
      batch: "B-7721",
      inspector: "Omar Diaz",
      inspected: 400,
      rejected: 0,
      date: "2026-08-19",
      status: "pass",
    },
  ],
  warehouses: [
    { id: "w1", name: "Warehouse A", zones: ["Raw Materials", "WIP", "Packaging"] },
    { id: "w2", name: "Warehouse B", zones: ["Finished Goods", "Returns"] },
  ],
  invoices: [
    {
      id: "inv1",
      number: "INV-5521",
      type: "receivable",
      partyName: "Northline Automotive",
      date: "2026-08-01",
      dueDate: "2026-08-31",
      amount: 43200,
      paid: 0,
      status: "overdue",
    },
    {
      id: "inv2",
      number: "INV-5518",
      type: "receivable",
      partyName: "Pacific Rail Parts",
      date: "2026-08-10",
      dueDate: "2026-09-09",
      amount: 22100,
      paid: 0,
      status: "open",
    },
    {
      id: "inv3",
      number: "BILL-2201",
      type: "payable",
      partyName: "Texas Steel Supply",
      date: "2026-08-20",
      dueDate: "2026-08-27",
      amount: 2304,
      paid: 0,
      status: "open",
    },
    {
      id: "inv4",
      number: "BILL-2190",
      type: "payable",
      partyName: "Polymer Plus",
      date: "2026-08-05",
      dueDate: "2026-08-26",
      amount: 8400,
      paid: 0,
      status: "open",
    },
    {
      id: "inv5",
      number: "INV-5502",
      type: "receivable",
      partyName: "Gulf Coast Energy",
      date: "2026-07-15",
      dueDate: "2026-08-29",
      amount: 76000,
      paid: 76000,
      status: "paid",
    },
  ],
  bankAccounts: [
    { id: "b1", name: "Operating — First National", type: "bank", balance: 100000 },
    { id: "b2", name: "Payroll — First National", type: "bank", balance: 42000 },
    { id: "b3", name: "Petty Cash", type: "cash", balance: 8500 },
  ],
  employees: [
    { id: "e1", name: "Mike Torres", department: "Fabrication", role: "Cutter", shift: "morning", status: "active", hourlyRate: 28 },
    { id: "e2", name: "Ana Lopez", department: "Machining", role: "CNC Operator", shift: "morning", status: "active", hourlyRate: 32 },
    { id: "e3", name: "Chris Park", department: "Assembly", role: "Assembler", shift: "evening", status: "active", hourlyRate: 24 },
    { id: "e4", name: "Nina Brooks", department: "QC", role: "Inspector", shift: "morning", status: "active", hourlyRate: 30 },
    { id: "e5", name: "Ravi Patel", department: "Maintenance", role: "Technician", shift: "morning", status: "active", hourlyRate: 34 },
    { id: "e6", name: "Sofia Nguyen", department: "Sales", role: "Account Exec", shift: "morning", status: "active", hourlyRate: 0 },
    { id: "e7", name: "Jamal Wright", department: "Warehouse", role: "Picker", shift: "night", status: "leave", hourlyRate: 22 },
    { id: "e8", name: "Helen Cho", department: "Accounts", role: "Controller", shift: "morning", status: "active", hourlyRate: 0 },
  ],
  alerts: [
    {
      id: "a1",
      severity: "critical",
      module: "Inventory",
      title: "Steel Sheet 2mm below reorder level",
      detail: "Available 3,500 KG · Reorder at 500 KG buffer stressed by PR-1026 demand",
      time: "12 min ago",
    },
    {
      id: "a2",
      severity: "warning",
      module: "Production",
      title: "Production Order PR-1023 delayed",
      detail: "Motor Housing X · 62% complete · deadline Sept 12 at risk",
      time: "41 min ago",
    },
    {
      id: "a3",
      severity: "warning",
      module: "Accounts",
      title: "Customer invoice overdue",
      detail: "INV-5521 · Northline Automotive · $43,200",
      time: "2 hr ago",
    },
    {
      id: "a4",
      severity: "info",
      module: "Purchase",
      title: "Supplier payment due tomorrow",
      detail: "BILL-2201 · Texas Steel Supply · $2,304",
      time: "3 hr ago",
    },
    {
      id: "a5",
      severity: "warning",
      module: "Maintenance",
      title: "Machine maintenance due",
      detail: "Laser Cutter #03 · 12 hours until service window",
      time: "5 hr ago",
    },
    {
      id: "a6",
      severity: "critical",
      module: "Quality",
      title: "Quality issue detected",
      detail: "PR-1015 final inspection · 3% rejection on flange tolerance",
      time: "6 hr ago",
    },
  ],
  aiInsights: [
    {
      id: "ai1",
      question: "Why did our profit decrease this month?",
      answer:
        "Gross profit decreased 8.4%. The primary causes were a 12% increase in steel costs and a 6.2% increase in production scrap. Product Motor Housing X contributed 63% of the margin decline.",
      metrics: [
        { label: "Gross profit Δ", value: "-8.4%", trend: "down" },
        { label: "Steel cost Δ", value: "+12%", trend: "up" },
        { label: "Scrap rate Δ", value: "+6.2%", trend: "up" },
        { label: "Housing X share of decline", value: "63%", trend: "flat" },
      ],
    },
    {
      id: "ai2",
      question: "Will we run out of steel?",
      answer:
        "Steel inventory will likely run out in 9 days based on current production schedules for PR-1026 and PR-1023. PO-4412 (1,200 KG) is expected Aug 27 and closes most of the gap if received on time.",
      metrics: [
        { label: "Days of cover", value: "9 days", trend: "down" },
        { label: "Open PO inbound", value: "1,200 KG", trend: "up" },
        { label: "Shortage vs PR-1026", value: "1,200 KG", trend: "flat" },
      ],
    },
    {
      id: "ai3",
      question: "Which line is underperforming?",
      answer:
        "Production Line 2 (Laser Cutter #03) is 17% less efficient this week versus plant average. Downtime ahead of preventive maintenance and rework from flange tolerance failures are the main drivers.",
      metrics: [
        { label: "Line 2 efficiency", value: "71%", trend: "down" },
        { label: "Plant average", value: "85%", trend: "flat" },
        { label: "Gap", value: "-17%", trend: "down" },
      ],
    },
  ],
  metrics: {
    revenue: 125400,
    salesOrders: 38,
    productionOrders: 24,
    pendingOrders: 11,
    lowStockItems: 7,
    purchaseOrders: 14,
    receivables: 43200,
    payables: 28500,
    cashBalance: 150500,
  },
  revenueTrend: [
    { month: "Mar", revenue: 98000, cogs: 62000, profit: 36000 },
    { month: "Apr", revenue: 104000, cogs: 65000, profit: 39000 },
    { month: "May", revenue: 112000, cogs: 71000, profit: 41000 },
    { month: "Jun", revenue: 118000, cogs: 76000, profit: 42000 },
    { month: "Jul", revenue: 131000, cogs: 82000, profit: 49000 },
    { month: "Aug", revenue: 125400, cogs: 86000, profit: 39400 },
  ],
  productionTrend: [
    { day: "Mon", planned: 420, actual: 400 },
    { day: "Tue", planned: 420, actual: 415 },
    { day: "Wed", planned: 450, actual: 390 },
    { day: "Thu", planned: 450, actual: 440 },
    { day: "Fri", planned: 400, actual: 385 },
    { day: "Sat", planned: 200, actual: 210 },
  ],
  decisions: [],
  decisionSettings: {
    autoExecute: false,
    requireApprovalForCritical: true,
    enableShortageRule: true,
    enableOverdueHoldRule: true,
    enableQcBlockRule: true,
    enableMaintenanceRule: true,
    enableMarginRule: true,
  },
  dispatchHolds: [],
  qcBlocks: [],
};

export function availableQty(p: { quantity: number; reserved: number }) {
  return p.quantity - p.reserved;
}

export function quoteTotal(q: {
  lines: { quantity: number; unitPrice: number }[];
  taxRate: number;
  discount: number;
}) {
  const subtotal = q.lines.reduce((s, l) => s + l.quantity * l.unitPrice, 0);
  const tax = subtotal * q.taxRate;
  return { subtotal, tax, total: subtotal + tax - q.discount };
}

export function materialRequirements(
  bomLines: { productId: string; quantity: number }[],
  orderQty: number,
  products: { id: string; quantity: number; reserved: number; name: string; unit: string }[]
) {
  return bomLines.map((line) => {
    const product = products.find((p) => p.id === line.productId)!;
    const required = line.quantity * orderQty;
    const available = availableQty(product);
    return {
      productId: line.productId,
      name: product.name,
      unit: product.unit,
      perUnit: line.quantity,
      required,
      available,
      shortage: Math.max(0, required - available),
    };
  });
}
