import Proposal from '../models/Proposal.js';
import Call from '../models/Call.js';
import Client from '../models/Client.js';
import Notification from '../models/Notification.js';
import Organization from '../models/Organization.js';
import { generateProposal, generateFollowUp } from '../services/aiService.js';
import { makeSlug, makeToken } from '../utils/slug.js';
import PDFDocument from 'pdfkit';

function pushEvent(proposal, type, label, meta = {}) {
  proposal.events.push({ type, label, meta, at: new Date() });
}

export async function listProposals(req, res) {
  const proposals = await Proposal.find({ organization: req.user.organization })
    .populate('client', 'companyName contactName contactEmail')
    .populate('call', 'title status')
    .sort({ updatedAt: -1 });
  return res.json({ proposals });
}

export async function getProposal(req, res) {
  const proposal = await Proposal.findOne({ _id: req.params.id, organization: req.user.organization })
    .populate('client')
    .populate('call')
    .populate('owner', 'name email');
  if (!proposal) return res.status(404).json({ message: 'Proposal not found' });
  return res.json({ proposal });
}

export async function generateFromCall(req, res) {
  try {
    const call = await Call.findOne({ _id: req.params.callId, organization: req.user.organization }).populate('client');
    if (!call) return res.status(404).json({ message: 'Call not found' });
    if (!call.analysis) {
      return res.status(400).json({ message: 'Analyze the call before generating a proposal' });
    }

    const unanswered = (call.analysis.missingInformation || []).filter((m) => !m.answered);
    const force = Boolean(req.body.force);
    if (unanswered.length && !force) {
      return res.status(409).json({
        message: 'Important details are missing before generating the proposal.',
        missingInformation: unanswered,
        canForce: true,
      });
    }

    const generated = await generateProposal(call, call.client, call.analysis);
    const template = req.body.template || 'modern';

    let proposal = await Proposal.findOne({ call: call._id });
    if (proposal) {
      Object.assign(proposal, {
        ...generated,
        template,
        status: 'ready',
        version: proposal.version + 1,
      });
      pushEvent(proposal, 'edited', 'Proposal regenerated from AI');
      await proposal.save();
    } else {
      proposal = await Proposal.create({
        organization: req.user.organization,
        client: call.client._id,
        call: call._id,
        owner: req.user._id,
        slug: makeSlug(`${call.client.companyName}-proposal`),
        publicToken: makeToken(),
        template,
        status: 'ready',
        ...generated,
        events: [{ type: 'created', label: 'Proposal generated by AI', at: new Date() }],
      });
    }

    call.proposal = proposal._id;
    call.status = 'proposal_ready';
    await call.save();

    await Organization.findByIdAndUpdate(req.user.organization, {
      $inc: { 'usage.proposalsThisMonth': 1 },
    });

    const populated = await Proposal.findById(proposal._id).populate('client').populate('call');
    return res.status(201).json({ proposal: populated });
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
}

export async function updateProposal(req, res) {
  try {
    const proposal = await Proposal.findOne({ _id: req.params.id, organization: req.user.organization });
    if (!proposal) return res.status(404).json({ message: 'Proposal not found' });

    const allowed = [
      'title',
      'template',
      'content',
      'packages',
      'selectedPackageId',
      'investment',
      'timelineDisplay',
      'status',
    ];
    for (const key of allowed) {
      if (req.body[key] !== undefined) proposal[key] = req.body[key];
    }

    if (req.body.selectedPackageId) {
      const pkg = proposal.packages.find((p) => p.id === req.body.selectedPackageId);
      if (pkg) proposal.investment = pkg.price;
    }

    pushEvent(proposal, 'edited', 'Proposal updated in editor');
    proposal.version += 1;
    await proposal.save();
    return res.json({ proposal });
  } catch (error) {
    return res.status(400).json({ message: error.message });
  }
}

export async function sendProposal(req, res) {
  try {
    const proposal = await Proposal.findOne({ _id: req.params.id, organization: req.user.organization })
      .populate('client')
      .populate('owner', 'name email');
    if (!proposal) return res.status(404).json({ message: 'Proposal not found' });

    proposal.status = 'sent';
    proposal.sentAt = new Date();
    pushEvent(proposal, 'sent', `Sent to ${proposal.client.contactEmail || proposal.client.contactName || 'client'}`);
    await proposal.save();

    await Call.findByIdAndUpdate(proposal.call, { status: 'sent' });
    await Client.findByIdAndUpdate(proposal.client._id, { status: 'proposal' });

    const publicUrl = `${process.env.CLIENT_URL || 'http://localhost:5173'}/p/${proposal.slug}`;

    return res.json({
      proposal,
      publicUrl,
      emailPreview: {
        to: proposal.client.contactEmail || 'client@example.com',
        subject: `${proposal.title}`,
        body: `Hi ${(proposal.client.contactName || 'there').split(' ')[0]},\n\nI've put together a proposal for ${proposal.client.companyName}. You can review it here:\n${publicUrl}\n\nBest,\n${proposal.owner.name}`,
      },
    });
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
}

export async function getPublicProposal(req, res) {
  const proposal = await Proposal.findOne({ slug: req.params.slug })
    .populate('client', 'companyName contactName contactTitle contactEmail')
    .populate('owner', 'name email')
    .populate('organization', 'name brand');

  if (!proposal) return res.status(404).json({ message: 'Proposal not found' });
  if (!['sent', 'viewed', 'changes_requested', 'accepted', 'declined'].includes(proposal.status) && req.query.preview !== '1') {
    // Allow preview token via owner app; public needs sent+
  }

  return res.json({
    proposal: {
      id: proposal._id,
      title: proposal.title,
      slug: proposal.slug,
      template: proposal.template,
      status: proposal.status,
      content: proposal.content,
      packages: proposal.packages,
      selectedPackageId: proposal.selectedPackageId,
      investment: proposal.investment,
      timelineDisplay: proposal.timelineDisplay,
      client: proposal.client,
      owner: proposal.owner,
      organization: proposal.organization,
      sentAt: proposal.sentAt,
      acceptedAt: proposal.acceptedAt,
      changeRequest: proposal.changeRequest,
    },
  });
}

export async function trackPublicEvent(req, res) {
  try {
    const proposal = await Proposal.findOne({ slug: req.params.slug }).populate('client').populate('owner');
    if (!proposal) return res.status(404).json({ message: 'Proposal not found' });

    const { type, seconds = 0 } = req.body;
    const now = new Date();

    if (type === 'opened') {
      if (!proposal.firstOpenedAt) proposal.firstOpenedAt = now;
      proposal.lastViewedAt = now;
      proposal.openCount += 1;
      if (['sent', 'viewed'].includes(proposal.status)) proposal.status = 'viewed';
      const label = proposal.openCount === 1
        ? `${proposal.client.contactName || 'Client'} opened proposal`
        : `${proposal.client.contactName || 'Client'} returned to proposal`;
      pushEvent(proposal, proposal.openCount === 1 ? 'opened' : 'returned', label);
      await Notification.create({
        organization: proposal.organization,
        user: proposal.owner._id || proposal.owner,
        type: 'proposal_opened',
        title: 'Proposal opened',
        body: label,
        link: `/proposals/${proposal._id}`,
      });
    }

    if (type === 'viewed_pricing') {
      proposal.lastViewedAt = now;
      pushEvent(proposal, 'viewed_pricing', 'Viewed pricing');
    }

    if (type === 'heartbeat') {
      proposal.totalViewTimeSeconds += Number(seconds) || 0;
      proposal.lastViewedAt = now;
    }

    if (type === 'requested_changes') {
      proposal.status = 'changes_requested';
      proposal.changeRequest = req.body.message || 'Client requested changes';
      pushEvent(proposal, 'requested_changes', 'Requested changes', { message: proposal.changeRequest });
      await Notification.create({
        organization: proposal.organization,
        user: proposal.owner._id || proposal.owner,
        type: 'proposal_changes',
        title: 'Changes requested',
        body: `${proposal.client.companyName} requested changes to the proposal.`,
        link: `/proposals/${proposal._id}`,
      });
    }

    if (type === 'accepted') {
      proposal.status = 'accepted';
      proposal.acceptedAt = now;
      pushEvent(proposal, 'accepted', 'Accepted proposal');
      await Call.findByIdAndUpdate(proposal.call, { status: 'won' });
      await Client.findByIdAndUpdate(proposal.client._id || proposal.client, { status: 'won' });
      await Notification.create({
        organization: proposal.organization,
        user: proposal.owner._id || proposal.owner,
        type: 'proposal_accepted',
        title: 'Deal won',
        body: `${proposal.client.companyName} accepted — $${Number(proposal.investment).toLocaleString()}`,
        link: `/proposals/${proposal._id}`,
      });
    }

    if (type === 'declined') {
      proposal.status = 'declined';
      pushEvent(proposal, 'declined', 'Declined proposal');
      await Call.findByIdAndUpdate(proposal.call, { status: 'lost' });
      await Client.findByIdAndUpdate(proposal.client._id || proposal.client, { status: 'lost' });
    }

    await proposal.save();
    return res.json({ ok: true, status: proposal.status, totalViewTimeSeconds: proposal.totalViewTimeSeconds });
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
}

export async function followUp(req, res) {
  try {
    const proposal = await Proposal.findOne({ _id: req.params.id, organization: req.user.organization }).populate('client');
    if (!proposal) return res.status(404).json({ message: 'Proposal not found' });

    const tone = req.body.tone || 'professional';
    const day = Number(req.body.day) || 2;
    const draft = await generateFollowUp({ client: proposal.client, proposal, tone, day });

    if (req.body.markSent) {
      pushEvent(proposal, 'follow_up_sent', `Follow-up sent (${tone}, day ${draft.day})`);
      await proposal.save();
    }

    return res.json({ followUp: draft });
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
}

export async function downloadPdf(req, res) {
  try {
    const proposal = await Proposal.findOne({ _id: req.params.id, organization: req.user.organization })
      .populate('client')
      .populate('owner', 'name');
    if (!proposal) return res.status(404).json({ message: 'Proposal not found' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${proposal.slug}.pdf"`);

    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);
    doc.fontSize(22).text(proposal.client.companyName, { continued: false });
    doc.moveDown(0.3);
    doc.fontSize(14).fillColor('#334155').text(proposal.title);
    doc.moveDown();
    doc.fillColor('#0f172a').fontSize(11).text(`Prepared by ${proposal.owner.name}`);
    doc.text(`Investment: $${Number(proposal.investment).toLocaleString()}`);
    doc.text(`Timeline: ${proposal.timelineDisplay || 'TBD'}`);
    doc.moveDown();
    doc.fontSize(13).text('Project Overview');
    doc.fontSize(10).fillColor('#334155').text(proposal.content.projectOverview || '');
    doc.moveDown();
    doc.fillColor('#0f172a').fontSize(13).text('Scope of Work');
    (proposal.content.scopeOfWork || []).forEach((item) => {
      doc.fontSize(10).fillColor('#334155').text(`${String(item.order).padStart(2, '0')} — ${item.title}`);
      if (item.description) doc.fontSize(9).fillColor('#64748b').text(item.description, { indent: 12 });
    });
    doc.moveDown();
    doc.fillColor('#0f172a').fontSize(13).text('Timeline');
    (proposal.content.timeline || []).forEach((item) => {
      doc.fontSize(10).fillColor('#334155').text(`${item.week} — ${item.title}`);
    });
    doc.end();
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
}

export async function trackingTimeline(req, res) {
  const proposal = await Proposal.findOne({ _id: req.params.id, organization: req.user.organization })
    .populate('client', 'companyName contactName');
  if (!proposal) return res.status(404).json({ message: 'Proposal not found' });

  const minutes = Math.floor(proposal.totalViewTimeSeconds / 60);
  const seconds = proposal.totalViewTimeSeconds % 60;

  return res.json({
    proposalId: proposal._id,
    status: proposal.status,
    openCount: proposal.openCount,
    totalViewTime: `${minutes}m ${seconds}s`,
    firstOpenedAt: proposal.firstOpenedAt,
    lastViewedAt: proposal.lastViewedAt,
    events: proposal.events,
  });
}
