import { formatPkr } from "../money.js";

export type RoiPdfInput = {
  institutionName: string;
  brandPrimary?: string | null;
  period: string;
  headlinePaisa: number;
  headlineText: string;
  inquiriesAnswered: number;
  avgFirstResponseMinutes: number;
  visitsBooked: number;
  admissionsWon: number;
  admissionsAnnualFeePaisa: number;
  feesRecoveredByAutomationPaisa: number;
  tutorIncomePaisa: number;
  messagesSent: number;
  readRatePct: number;
  atRiskStudentsSaved: number;
};

/** Branded printable HTML — open and Print → Save as PDF. */
export function buildRoiReportHtml(input: RoiPdfInput): string {
  const ink = input.brandPrimary || "#0E1B2C";
  const rows: Array<[string, string]> = [
    ["Inquiries answered", String(input.inquiriesAnswered)],
    ["Avg first response", `${input.avgFirstResponseMinutes} min`],
    ["Visits booked", String(input.visitsBooked)],
    ["Admissions won", String(input.admissionsWon)],
    ["Admissions annual value", formatPkr(input.admissionsAnnualFeePaisa)],
    ["Fees recovered by automation", formatPkr(input.feesRecoveredByAutomationPaisa)],
    ["Tutor income", formatPkr(input.tutorIncomePaisa)],
    ["Messages sent / read rate", `${input.messagesSent} · ${input.readRatePct}%`],
    ["At-risk students saved", String(input.atRiskStudentsSaved)],
  ];

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Maxtrone ROI — ${escapeHtml(input.period)}</title>
<style>
  @page { margin: 24mm; }
  body { font-family: "DM Sans", system-ui, sans-serif; color: #3D4757; background: #F6F3EC; margin: 0; padding: 32px; }
  .sheet { max-width: 720px; margin: 0 auto; background: #FFFDF8; border: 1px solid #E4DDCC; border-radius: 16px; padding: 40px; }
  h1 { font-family: Georgia, "Fraunces", serif; color: ${ink}; font-size: 28px; margin: 0 0 8px; }
  .brand { letter-spacing: 0.04em; text-transform: uppercase; font-size: 12px; color: #8A6A1F; }
  .headline { font-family: Georgia, serif; font-size: 22px; color: #C9A24A; margin: 24px 0; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; }
  td { padding: 10px 0; border-bottom: 1px solid #E4DDCC; font-variant-numeric: tabular-nums; }
  td:last-child { text-align: right; font-weight: 600; color: ${ink}; }
  .footer { margin-top: 32px; font-size: 12px; color: #8a8478; }
</style>
</head>
<body>
  <div class="sheet">
    <p class="brand">Maxtrone · Monthly ROI</p>
    <h1>${escapeHtml(input.institutionName)}</h1>
    <p>Period ${escapeHtml(input.period)}</p>
    <p class="headline">${escapeHtml(input.headlineText)}</p>
    <table>
      ${rows.map(([k, v]) => `<tr><td>${escapeHtml(k)}</td><td>${escapeHtml(v)}</td></tr>`).join("")}
    </table>
    <p class="footer">Attribution: fees recovered within 72h of an automated reminder · Generated by Maxtrone Campus</p>
  </div>
</body>
</html>`;
}

export type ReportCardPdfInput = {
  institutionName: string;
  studentName: string;
  registrationNo?: string | null;
  termLabel: string;
  subjects: Array<{ title: string; score: number; total: number; rank?: number | null; weakTopics?: string[] }>;
};

export function buildReportCardHtml(input: ReportCardPdfInput): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Report card — ${escapeHtml(input.studentName)}</title>
<style>
  @page { margin: 18mm; }
  body { font-family: "DM Sans", system-ui, sans-serif; color: #3D4757; background: #F6F3EC; margin: 0; padding: 24px; }
  .sheet { max-width: 640px; margin: 0 auto; background: #FFFDF8; border: 1px solid #E4DDCC; border-radius: 16px; padding: 36px; }
  h1 { font-family: Georgia, serif; color: #0E1B2C; margin: 0; }
  .meta { color: #8a8478; font-size: 13px; margin-top: 6px; }
  table { width: 100%; border-collapse: collapse; margin-top: 28px; }
  th, td { text-align: left; padding: 10px 8px; border-bottom: 1px solid #E4DDCC; font-variant-numeric: tabular-nums; }
  th { font-size: 12px; text-transform: uppercase; letter-spacing: 0.04em; color: #8A6A1F; }
  .weak { font-size: 12px; color: #B42318; }
</style>
</head>
<body>
  <div class="sheet">
    <p class="meta">${escapeHtml(input.institutionName)}</p>
    <h1>${escapeHtml(input.studentName)}</h1>
    <p class="meta">${escapeHtml(input.termLabel)}${input.registrationNo ? ` · ${escapeHtml(input.registrationNo)}` : ""}</p>
    <table>
      <thead><tr><th>Assessment</th><th>Score</th><th>Rank</th><th>Focus</th></tr></thead>
      <tbody>
        ${input.subjects
          .map(
            (s) => `<tr>
          <td>${escapeHtml(s.title)}</td>
          <td>${s.score}/${s.total}</td>
          <td>${s.rank ?? "—"}</td>
          <td class="weak">${escapeHtml((s.weakTopics ?? []).join(", ") || "—")}</td>
        </tr>`,
          )
          .join("")}
      </tbody>
    </table>
  </div>
</body>
</html>`;
}

/** Minimal valid PDF with a single text line (no external deps). */
export function buildMinimalPdf(lines: string[]): Uint8Array {
  const contentLines = lines.map((l, i) => `BT /F1 12 Tf 50 ${750 - i * 18} Td (${escapePdf(l)}) Tj ET`);
  const stream = contentLines.join("\n");
  const objects = [
    "1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj",
    "2 0 obj<< /Type /Pages /Kids [3 0 R] /Count 1 >>endobj",
    "3 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources<< /Font<< /F1 5 0 R >> >> >>endobj",
    `4 0 obj<< /Length ${stream.length} >>stream\n${stream}\nendstream endobj`,
    "5 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>endobj",
  ];
  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (const obj of objects) {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += obj + "\n";
  }
  const xrefStart = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i < offsets.length; i++) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;
  return new TextEncoder().encode(pdf);
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function escapePdf(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

/** Parse TSV/CSV pasted from Excel into student-score rows by index. */
export function parseMarksPaste(
  paste: string,
  students: Array<{ id: string }>,
): Array<{ studentId: string; score: number }> {
  const lines = paste
    .trim()
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean);
  const out: Array<{ studentId: string; score: number }> = [];
  for (let i = 0; i < lines.length && i < students.length; i++) {
    const cells = lines[i]!.split(/[\t,]/);
    const scoreCell = cells.length > 1 ? cells[cells.length - 1]! : cells[0]!;
    const score = Number(scoreCell.replace(/[^\d.-]/g, ""));
    if (!Number.isFinite(score)) continue;
    out.push({ studentId: students[i]!.id, score: Math.max(0, Math.round(score)) });
  }
  return out;
}
